name: tim25
channels:
  - conda-forge

dependencies:
  - python==3.10
  - jupyterlab
  - napari==0.5.6
  - pyqt==5.15.9
  - seaborn==0.13.2
  - napari-segment-blobs-and-things-with-membranes==0.3.11
  - napari-skimage-regionprops==0.10.1
  - napari-accelerated-pixel-and-object-classification==0.14.1
  - napari-clusters-plotter==0.8.1
  - omero-py==5.19.6
  - pip
  - pip:
    - napari-omero==0.4.0
